### ISSUE TITLE
Implement FontAwesome Icon Wrapper

### ISSUE THREAD

**Issue by ChengYanJin** [scality/core-ui#283]
**Component**: Icon

**Why this is needed**:
The purpose of is icon wrapper is to help us choose the good icon base on the usage instead of choosing a random one directly from FontAwesome. 

**What should be done**:
Create a new component `Icon`.
Following the [Iconography](https://github.com/scality/core-ui/pull/276), we want to implement a wrapper for all the icon lists in the PR.

Example:
![image](https://user-images.githubusercontent.com/18453133/112949301-5c24a180-9139-11eb-87da-749bac81dc6f.png)
when I call`<Icon name={"Theme"}/>` I will get directly the theme icon. 
Instead of `<i className="fas fa-palette" />`

**Implementation proposal** (strongly recommended):
Would be great if the implementation of <Icon name={"Theme"}/> lazy loads only the required icon

**Test plan**:
**Next step**: Will need to replace all the current icons directly from `fontawsome` by the iconwrapper from `core-ui`.

**Comment by JBWatenbergScality** [comment]
**Implementation detail :**
Would be great if the implementation of `<Icon name={"Theme"}/> ` lazy loads only the required icon

**Comment by theocerutti** [comment]
1/
In Iconography tab, is it normal that they are both called Dropdown? If not I would call them Dropdown-down / Dropdown-up.

![image](https://user-images.githubusercontent.com/44285344/113416682-1e867980-93c2-11eb-9443-4ee546ab971d.png)



2/
I think we can't do a lazy load for now since we import the whole css from font awesome directly (`import '@fortawesome/fontawesome-free/css/all.css'`).
We should add `@fortawesome/fontawesome-svg-core`, `@fortawesome/free-solid-svg-icons`, `@fortawesome/free-regular-svg-icons` and `@fortawesome/react-fontawesome` to do lazy loads only on the icons we are interested in. (and then we could remove `@fortawesome/fontawesome-free`).

We will then have to do (for example): 
```jsx
// In index.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { faWallet, faBackend, fa.... /* FOR ALL ICONS */ } from '@fortawesome/free-solid-svg-icons'; // for fas icons
import { faCircle } from ''@fortawesome/free-regular-svg-icons'; // for far icons
library.add(faWallet, faBackend, fa...)

// In Icon.component.js (really short example)
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export default function Icon () {
  return <FontAwesomeIcon icon="backend" />;
}
```

More information here: 
https://github.com/vercel/next.js/discussions/16027
https://fontawesome.com/how-to-use/on-the-web/using-with/react#using

Maybe there is another way to do it.. do you have any ideas ?

**Comment by JBWatenbergScality** [comment]
I think something like this should be fine (haven't tested this through so please considers this as pseudo code) :

```js
//@flow
import type {Node} from 'react';
import {Suspense} from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Loader from './Loader'

type IconName = "coffee" | "moon"

export function Icon({name}: {name: IconName}): Node {
  return <Suspense fallback={<Loader />}><LazyIcon name={name} /></Suspense>
}

function LazyFa({name}: {name: string}): Node {
  return React.lazy(import(`@fortawesome/free-solid-svg-icons/${name}`).then(icon => <FontAwesomeIcon icon={icon} />  ))
}

function LazyIcon({name}: {name: IconName}): Node {
  switch(name) {
     case "coffee":
        return <LazyFa name="faCoffee"/>
    case "moon":
        return <LazyFa name="faMoon"/>
   //...
  }

}


// Sample
const element = <Icon icon={faCoffee} />
```

**Comment by theocerutti** [comment]
@JBWatenbergScality Unfortunately, fontAwesome does not provide a way to import the icons like this
```js
import(`@fortawesome/free-solid-svg-icons/${nameOfTheIcon}`)
```

We can do
```js
return React.lazy(async () => {
    const module = await import('@fortawesome/free-regular-svg-icons');
    return { default: (props) => <FontAwesomeIcon icon={module['IconIWantToRender']} /> }
})
```
but the problem is that we have to import the whole module.. Do you think it's an issue?

I think the best way is to use the official `@fortawesome/fontawesome-svg-core` package as I said in my previous message.

**Comment by JBWatenbergScality** [comment]
Hello,

Just made a test and fontAwesome is exporting the icon individually as part of this package.

Here is a demo : https://codesandbox.io/s/beautiful-moore-n6xgr?file=/src/App.js
