### ISSUE TITLE
Steppers: styles improvement

### ISSUE THREAD

**Issue by carlito-scality** [scality/core-ui#43]
**Component**: Steeper

**Why this is needed**:
- ```title ``` props should be a component instead of a string so that we can customize it.
- We would like to display a `activeStep` in error with  background-color `red` in the `Circle`. We need to add `error` in the props.
-  We would like to display a `activeStep` in progress with the "scality loader" (or something else to make it more visible) in the `Circle`. We need to add `inProgress` in the props.

**What should be done**:

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by StheffanyHadlich** [comment]
Can I help here?

**Comment by carlito-scality** [comment]
> Can I help here?

Hello @StheffanyHadlich ! sure. I just updated the description. If you have questions, please ask before implementing. 
Thanks :)

**Comment by StheffanyHadlich** [comment]
@carlito-scality the `error` prop should have precedent over active? For example if a node is active but also have `error == true` what should be its background color?

**Comment by StheffanyHadlich** [comment]
@carlito-scality  I have a question about using _scality loader_ because its default `fill` css property is the same dark color as the `active` Node from the _Steppers Component_. I tried pass `color` as a prop to _Loader_ but I notice it doesn't have influence to its `fill` css property.

I opened an WIP PR (#145) to this issue, there is a print there where I changed the `fill` property manually so it was visible. Not sure how to handle this properly.

| Loader default `fill` color | Loader manually changed's `fill` color |
| -------------------------- | --------------------------- |
| ![image](https://user-images.githubusercontent.com/31314523/70288760-69ce4f00-17b1-11ea-9c28-0b91739eabc6.png) | ![image](https://user-images.githubusercontent.com/31314523/70288700-355a9300-17b1-11ea-9ba3-7aa2a53ad48b.png) |

**Comment by carlito-scality** [comment]
> @carlito-scality the `error` prop should have precedent over active? For example if a node is active but also have `error == true` what should be its background color?

It should be red as well :)
A step could be:
- active => primary color
- active and inProgress => primary color with loader
- active and error => `danger` color

**Comment by carlito-scality** [comment]
> @carlito-scality I have a question about using _scality loader_ because its default `fill` css property is the same dark color as the `active` Node from the _Steppers Component_. I tried pass `color` as a prop to _Loader_ but I notice it doesn't have influence to its `fill` css property.
> 
> I opened an WIP PR (#145) to this issue, there is a print there where I changed the `fill` property manually so it was visible. Not sure how to handle this properly.
> 
> Loader default `fill` color	Loader manually changed's `fill` color
> ![image](https://user-images.githubusercontent.com/31314523/70288760-69ce4f00-17b1-11ea-9c28-0b91739eabc6.png)	![image](https://user-images.githubusercontent.com/31314523/70288700-355a9300-17b1-11ea-9ba3-7aa2a53ad48b.png)

Ideally, we should make the Loader to support the `inverted` mode. we can implement it later. In this case, we can manually change `fill` color to `${props => mergeTheme(props.theme, defaultTheme).text};` as you suggested
